[build]
  base = "client"
  command = "CI= npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_SOCKET_URL = "https://pvc-badge-ceremony.onrender.com" 