services:
  - type: web
    name: pvc-badge-ceremony
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 3001 